version: "^7.50.0 || @head"
export: |

    project "cURL"

        kind "StaticLib"

        files "lib/**.c"

        includedirs "lib"

        zpm.export [[
            includedirs "include"

            zpm.uses "Zefiros-Software/mbedTLS"

            defines { 
                "BUILDING_LIBCURL",
                "CURL_STATICLIB",
                "HTTP_ONLY", 
                "USE_MBEDTLS",
                "CURL_HIDDEN_SYMBOLS",
            }

            filter "system:not windows"
                defines "HAVE_CONFIG_H"
            
            filter {}
        ]]