sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: osx
    osx_image: xcode9.2
    language: generic
global:
  env:
  - PROJECT=cURL
  - PROJECT_TEMPLATE=default
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition cURL
notifications:
  slack:
    secure: ZwRoRV+u33l/gOQO+hswYNq3Oq1aoLvwe4ASsiWyseVA/XhbElOnreq5rO6CcLOCpX2iRFCcRx/F8ZhekBoztX0shMVqUh9uRHwReoSZjFZd4yFzC3Zcr/rENB48s8vE6u9Xi86OomRlCZCk9Fck0YhbnSo3RnbialJ+NgodzFEARWcHoYBdBMhYl0gfbmbaIH+g1Tptma6nWTDt6uAAVhoFMNz73fdIBjPhlB9Gqd/kC+qZzwVt2aXsFXt/wsE4bevJfYWdQxZBvCD8hsDJkV6V6Jtssg1jS6UUbMS+JMd0lTutrvJHUyYMppId+HpvNmU5Va9HWL7zW+71AeC24HEvbdyfNBwzTNqQB7EiQ3teMq8W+tMdjyDFcr3T44m7H2LhIesMmrFGup7m/kyxN3//WkxcfJ+AUzylm0jGtpLGSDTHTBVwVu/IMxnBL7gTuG9gB6LK34S99qcd7azxLElxt5221VIfMBC1GlpGKc6OHbHEd2f1BsEoy6lLE1UOa2ZAOrjNMT5NZ/iFvpCwVd4/68W0QjQSo6O627zjrAIewndZCdo3gqNlg0nsORtiqIaL8lAgJ2N5U7DQ4l6oc4c/kE0GHjkPipM40gCPi1jFN9RM0az0D8qdxebskaGJ3SE4ysBWrnQPSYYVXfmofI5eveR7cqkflm/pXCMsKpk=
